### PR TITLE
chore: [WIP] add CONTRIBUTING.md example

### PR DESCRIPTION
**Pull request by mattwr18**
I realize this is a work in progress, and I can edit it based on how you envision the work flow going. 
For example, you said something about maybe preferring forks/`PR`s from forks, which I can add instructions for. Curious to see why you are favoring that approach? I have certainly worked on projects where we had that workflow and others where we didn't. 

In the latest project, we had contributors added to a volunteers group that had write access directly to the repo. We did this because 1 we had encrypted env variables that were not exposed to our Travis CI builds, and therefore didn't have much choice. Also, nowadays GitHub makes it possible to protect certain branches, like `master` to prevent anyone, including owners of `PR`s from pushing to the protected branch. We could also have restrictions that require at least one approval for `PR`s to be merged, like I wrote in the docs, which means I think we would not need to worry about someone accidentally causing harm. I'm just imagining why you might prefer the fork approach though, so I'll let you respond and we can carry on the conversation.

### CODE REVIEW

**Comment by srsexton94** [comment]
Helllo Matt! Thank you for writing that out, I gave it a read through and it's very professional and pretty comprehensive!  I'll go ahead and merge the PR in now

As for the preference for forks/PR I mainly said as such to have that extra layer to prevent folks from unintentionally causing harm to the project (merging in something that didn't align with the project goals/intentions, bugs up a different key function, etc...)
But I wasn't aware that GitHub had that type of protective option!  If so perhaps we could protect the master branch to allow collaborators more access
(also in group projects I usually like to work in branches off of a `development` branch as well - would it make sense to protect the two then? `master` and `development`?)

Lastly, a branch naming convention I've found really helpful in the past is to add the collaborator's name (or another identifier, username, etc...) before the branch name (eg. `Sam/edit-view`, `Matt/home-styling`, etc...)
Does that sound good to you?  If so we could add it to the contributing.md

Thanks again and apologies for the slow response!

**Comment by mattwr18** [comment]
that sounds good to me! I will prepend my name from now on, if I don't forget :stuck_out_tongue: 
I will update the `CONTIBUTING.md`... I am moving next week though so I might not have time for a couple weeks.

**Comment by mattwr18** [comment]
Maybe you have already done it, but I think you need to be an owner of a repository to configure to protect certain branches... Here are the instructions, in case you haven't had a chance to do it yet. https://help.github.com/en/github/administering-a-repository/configuring-protected-branches

I would protect both, yes. I have worked on projects where they use the development branch as the base branch as well, so I'm familiar with that workflow as well. I can update the `CONTRIBUTING.md` to reflect this.

**Comment by srsexton94** [comment]
Awesome, thank you - the master and development branches are now both
protected, requiring one PR review each before merging

**Comment by srsexton94** [comment]
Perfect!  I'll be sure to document/update you on anything I update in the
meantime - best of luck with your move!

**Pull request merged**
